tasks:
  - init: |
      pnpm install
      pnpm build
    command: |
      pnpm dev

github:
  prebuilds:
   master: true
   branches: true
   pullRequests: true
   pullRequestsFromForks: true
   addBadge: true
   addCheck: true
   addLabel: gitpod

gitConfig:
  commit.gpgsign: "true"
  tag.gpgsign: "true"

vscode:
  extensions:
    - antfu.vite
    - voorjaar.windicss-intellisense
    - esbenp.prettier-vscode
    - editorconfig.editorconfig
    - johnsoncodehk.volar